import { v2 as cloudinary } from "cloudinary";
import stream from "stream";

export async function createPresentation(presentationData = []) {
  // Dynamic import for pptxgenjs
  const PptxGenJS = (await import("pptxgenjs")).default;
  const pptx = new PptxGenJS();

  const themeColor = "2F5597";
  const textColor = "FFFFFF";
  const contentColor = "000000";


  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: themeColor };
  titleSlide.addText("Agentic AI - Teaching Assistant", {
    x: 1, y: 2, w: 8, h: 1, fontSize: 36, color: textColor, bold: true, align: "center",
  });
  const topicTitle = presentationData?.[0]?.slide_title || "Lesson";
  titleSlide.addText(`Topic: ${topicTitle}`, {
    x: 1, y: 3, w: 8, h: 1, fontSize: 24, color: textColor, align: "center",
  });


  presentationData.forEach((slideData, index) => {
    if (index === 0) return;
    const slide = pptx.addSlide();

    slide.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: 10, h: 0.8, fill: { color: themeColor } });
    slide.addText(slideData?.slide_title || `Slide ${index + 1}`, {
      x: 0, y: 0, w: 10, h: 0.8, fontSize: 24, color: textColor, bold: true, align: "center",
    });

    const marginX = 0.5, marginY = 1.2, contentWidth = 9.0, contentHeight = 4.0;
    slide.addShape(pptx.ShapeType.rect, {
      x: marginX, y: marginY, w: contentWidth, h: contentHeight, line: { color: themeColor, width: 1.5 },
    });

    const bullets = (slideData?.bullet_points || []).map((pt) => `• ${pt}`).join("\n");
    let fontSize = 20;
    const len = bullets.length;
    if (len > 700) fontSize = 14;
    else if (len > 500) fontSize = 16;
    else if (len > 350) fontSize = 18;

    slide.addText(bullets, {
      x: marginX + 0.2, y: marginY + 0.2, w: contentWidth - 0.4, h: contentHeight - 0.3,
      fontSize, color: contentColor, align: "left", valign: "top", lineSpacing: 24, wrap: true, autoFit: true,
    });

    slide.addText("Generated by Agentic AI", {
      x: 7, y: 6.8, w: 3, h: 0.4, fontSize: 12, color: "666666", align: "right",
    });
  });

  const buffer = await pptx.write("nodebuffer");

  return new Promise((resolve, reject) => {
      const uploadStream = cloudinary.uploader.upload_stream(
          { 
            resource_type: "raw", 
            type: "upload",
            folder: "ai-teaching-assistant", 
            format: "pptx"
          },
          (error, result) => {
              if (error) reject(error);
              else resolve(result.secure_url);
          }
      );
      const bufferStream = new stream.PassThrough();
      bufferStream.end(buffer);
      bufferStream.pipe(uploadStream);
  });
}
